---
title: "3D Landscapes"
author: "Antonia Netzl"
date: "2024-03-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r}
setwd("~/Documents/smith/labbook/roessler_et_al_2024_dev/")
library(Racmacs)
library(tidyverse)
library(r3js)
library(ablandscapes)
library(htmlwidgets)

set.seed(100)
# set optimization nr to fit BA.4/5 position; optimization nr 56 gives upper BA.4/5

map <- read.acmap(file.path("data", "maps", "map_threshold20_all_ags_singleTP_woXBBconvStudy_alpha_adj.ace"))
lims <- Racmacs:::mapPlotLims(map, sera = FALSE)

idvl_lndscp_list <- readRDS(file.path("data", "landscape_fit", "idvl_fits_ags_all.rds"))
lndscp_list <- readRDS(file.path("data", "landscape_fit", "biv_boosts_ags_all.rds"))
```

# Base map

```{r, out.width='75%'}
plot(map, plot_labels = "antigens", label.offset = c(1.5),
label.size = 0.5,
  xlim = lims$xlim, ylim = lims$ylim)
```

## Individual and GMT landscapes

### Wuhan vax (single dose)

```{r}
idvl_lndscp_list[["Wuhanvax.(singledose)"]]
```


### Wuhan vax (2 dose)
```{r}
idvl_lndscp_list[["Wuhanvax.(twodoses)"]]
```

### Wuhan conv.
```{r}
idvl_lndscp_list$Wuhanconv.
```

### Alpha conv.

```{r}
idvl_lndscp_list[["alphaconv." ]]
```

### Beta vax (single dose)

```{r}
idvl_lndscp_list[["Betavax.(singledose)"]]
```

### Betaconv.

```{r}
idvl_lndscp_list[["betaconv." ]]
```

### Gamma conv.

```{r}
idvl_lndscp_list[["gammaconv." ]]
```

### Delta conv.

```{r}
idvl_lndscp_list[["deltaconv." ]]
```

### BA.1 conv.

```{r}
idvl_lndscp_list[["BA.1conv."]]
```

### BA.2.12.1 conv.

```{r}
idvl_lndscp_list[["BA.2.12.1conv."]]
```

### BA.4 conv.

```{r}
idvl_lndscp_list[["BA.4conv."]]
```

### BA.5 conv.

```{r}
idvl_lndscp_list[["BA.5conv."]]
```

### BQ.1.1 conv.

```{r}
idvl_lndscp_list[["BQ.1.1conv."]]
```

### XBB conv.

```{r}
idvl_lndscp_list[["XBBconv."]]
```

### XBB.1.5 conv.

```{r}
idvl_lndscp_list[["XBB.1.5conv."]]
```

### XBB.1.5. vax (two doses)

```{r}
idvl_lndscp_list[["XBB.1.5vax.(twodoses)"]]
```


## GMT Antibody Landscapes
```{r}
lndscp_list$all
```